spring.application.name=bookclub
# MongoDB Configuration
spring.mongodb.database=bookclub
spring.mongodb.uri=mongodb+srv://bookclub_user:admin@cluster0.0dznvw3.mongodb.net/bookclub?retryWrites=true&w=majority
